# Generated by Django 5.0 on 2023-12-07 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobApplication', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='application_id',
        ),
        migrations.RemoveField(
            model_name='formal_education',
            name='formal_education_id',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_id',
        ),
        migrations.RemoveField(
            model_name='language_skills',
            name='language_skills_id',
        ),
        migrations.RemoveField(
            model_name='work_experience',
            name='work_experience_id',
        ),
    ]
