# Generated by Django 5.0 on 2023-12-07 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobApplication', '0003_remove_application_application_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='is_accepted',
        ),
        migrations.RemoveField(
            model_name='application',
            name='is_hired',
        ),
        migrations.RemoveField(
            model_name='application',
            name='is_interviewed',
        ),
        migrations.RemoveField(
            model_name='application',
            name='is_rejected',
        ),
        migrations.RemoveField(
            model_name='application',
            name='is_reviewed',
        ),
        migrations.RemoveField(
            model_name='application',
            name='is_shortlisted',
        ),
        migrations.RemoveField(
            model_name='application',
            name='is_submitted',
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('temporary', 'Temporary'), ('internship', 'Internship')], default='full_time', max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobApplication.job'),
        ),
        migrations.AlterField(
            model_name='formal_education',
            name='degree',
            field=models.CharField(choices=[('Bachelor', 'Bachelor'), ('Master', 'Master'), ('PhD', 'PhD'), ('Associate', 'Associate'), ('Diploma', 'Diploma'), ('Certificate', 'Certificate'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='formal_education',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formal_education',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formal_education',
            name='grade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='postedDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='requirements',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='language_skills',
            name='reading',
            field=models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('fluent', 'Fluent'), ('native', 'Native')], max_length=100),
        ),
        migrations.AlterField(
            model_name='language_skills',
            name='speaking',
            field=models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('fluent', 'Fluent'), ('native', 'Native')], max_length=100),
        ),
        migrations.AlterField(
            model_name='language_skills',
            name='writing',
            field=models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('fluent', 'Fluent'), ('native', 'Native')], max_length=100),
        ),
        migrations.AlterField(
            model_name='work_experience',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='work_experience',
            name='industry',
            field=models.CharField(blank=True, choices=[('Agriculture', 'Agriculture'), ('Banking', 'Banking'), ('Health', 'Health')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='work_experience',
            name='job_title',
            field=models.CharField(blank=True, choices=[('Software Engineer', 'Software Engineer'), ('Business Analyst', 'Business Analyst')], max_length=100, null=True),
        ),
    ]
