# Generated by Django 5.0 on 2023-12-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobApplication', '0004_remove_application_is_accepted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='date_applied',
            field=models.DateField(auto_now_add=True),
        ),
    ]
