# Generated by Django 5.0 on 2023-12-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobApplication', '0005_alter_application_date_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('interviewed', 'Interviewed'), ('shortlisted', 'Shortlisted'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('hired', 'Hired'), ('on_hold', 'On Hold')], default='on_hold', max_length=100),
        ),
    ]
