# Generated by Django 4.2.7 on 2023-12-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('interviewed', 'Interviewed'), ('shortlisted', 'Shortlisted'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='submitted', max_length=100)),
                ('date_applied', models.DateField(auto_now_add=True)),
                ('cv', models.FileField(upload_to='application_files/')),
                ('cover_letter', models.FileField(blank=True, null=True, upload_to='application_files/')),
            ],
            options={
                'db_table': 'application',
                'ordering': ['-date_applied'],
            },
        ),
        migrations.CreateModel(
            name='Formal_education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=100)),
                ('degree', models.CharField(choices=[('Bachelor', 'Bachelor'), ('Master', 'Master'), ('PhD', 'PhD'), ('Associate', 'Associate'), ('Diploma', 'Diploma'), ('Certificate', 'Certificate'), ('Other', 'Other')], max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('subject', models.CharField(max_length=100)),
                ('grade', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'formal_education',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('postedDate', models.DateField(auto_now_add=True)),
                ('deadline', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('salary', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=100)),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('temporary', 'Temporary'), ('internship', 'Internship')], default='full_time', max_length=100)),
                ('job_file', models.FileField(blank=True, null=True, upload_to='job_file/')),
            ],
            options={
                'db_table': 'job',
                'ordering': ['-postedDate'],
            },
        ),
        migrations.CreateModel(
            name='Language_skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('English', 'English'), ('French', 'French'), ('Arabic', 'Arabic'), ('Spanish', 'Spanish'), ('Portuguese', 'Portuguese'), ('Russian', 'Russian'), ('German', 'German'), ('Chinese', 'Chinese'), ('Japanese', 'Japanese'), ('Hindi', 'Hindi'), ('Turkish', 'Turkish'), ('Italian', 'Italian'), ('Persian', 'Persian'), ('Korean', 'Korean'), ('Vietnamese', 'Vietnamese'), ('Malay', 'Malay'), ('Kannada', 'Kannada'), ('Ukrainian', 'Ukrainian'), ('Romanian', 'Romanian'), ('Dutch', 'Dutch'), ('Kinyarwanda', 'Kinyarwanda'), ('Swahili', 'Swahili'), ('Mandarin', 'Mandarin'), ('Amharic', 'Amharic'), ('Yorùbá', 'Yorùbá'), ('Oromo', 'Oromo'), ('lingala', 'lingala')], max_length=100)),
                ('reading', models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('fluent', 'Fluent'), ('native', 'Native')], max_length=100)),
                ('writing', models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('fluent', 'Fluent'), ('native', 'Native')], max_length=100)),
                ('speaking', models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('fluent', 'Fluent'), ('native', 'Native')], max_length=100)),
            ],
            options={
                'db_table': 'language_skills',
            },
        ),
        migrations.CreateModel(
            name='Work_experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('is_present_employee', models.BooleanField(default=False)),
                ('end_date', models.DateField(blank=True, default=None, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, choices=[('Agriculture', 'Agriculture'), ('Banking', 'Banking'), ('Health', 'Health')], max_length=100, null=True)),
                ('job_title', models.CharField(blank=True, choices=[('Software Engineer', 'Software Engineer'), ('Business Analyst', 'Business Analyst')], max_length=100, null=True)),
            ],
            options={
                'db_table': 'work_experience',
                'ordering': ['-start_date'],
            },
        ),
    ]
