# Generated by Django 4.2.7 on 2024-01-12 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobApplication', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_file',
        ),
        migrations.AddField(
            model_name='job',
            name='english_job_description',
            field=models.FileField(default=None, upload_to='english_job_description_file/'),
        ),
        migrations.AddField(
            model_name='job',
            name='french_job_description',
            field=models.FileField(default=None, upload_to='french_job_description_file/'),
        ),
    ]
